# Generated by Django 4.2.16 on 2024-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualdef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meumodelo',
            name='destinatario',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='meumodelo',
            name='mensagem',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='meumodelo',
            name='remetente',
            field=models.TextField(default='', null=True),
        ),
    ]
